### ISSUE TITLE
make a "playerlist.*.json" and "rules.*.json" version

### ISSUE THREAD

**Issue by bobkinect98** [TheKing1543/TF2_Clowncheater_List#1]
instead of making what is entirely a fork of tf2bd, just make a `"rules.*.json"` or `"playerlist.*.json"` since [tf2bd has customization features](https://github.com/PazerOP/tf2_bot_detector/wiki/Customization#auto-detection-rules).  asking so people dont have to install a entirely different version for different rules and stuff

**Comment by TheKing1543** [comment]
Will do that!
